### ISSUE TITLE
PHPdoc Typehints in QuerySet can not be resolved

### ISSUE THREAD

**Issue by mfeldheim** [ihabunek/phormium#10]
In PHPStorm, the PHPdoc `@return` typehints in the class `QuerySet` are not correct, which causes warnings like `Expected Filter\Filter, got Phormium\Filter\Filter` or `Method not found` in the IDE

For example:

https://github.com/ihabunek/phormium/search?utf8=%E2%9C%93&q=%22%40var+Phormium%22&type=Code

https://github.com/ihabunek/phormium/search?utf8=%E2%9C%93&q=%22%40return+Phormium%22&type=Code

**Comment by ihabunek** [comment]
Don't use PHPStorm so can't reproduce. PR welcome.

**Comment by mfeldheim** [comment]
PR coming
