### ISSUE TITLE
Model::toYAML

### ISSUE THREAD

**Issue by mfeldheim** [ihabunek/phormium#14]
Method call uses 1 parameters, but method signature uses 0 parameters
https://github.com/ihabunek/phormium/blob/ac04ee58e701d0139af144cacf6e1852596fac27/src/Phormium/Model.php#L368

``` php
public function toYAML()
{
    return Yaml::dump(self::toArray($this));
}

public function toArray()
{
        return (array) $this;
}
```

**Comment by ihabunek** [comment]
Fixed in 000be66a.
