### ISSUE TITLE
Is it possible to override field / column names?

### ISSUE THREAD

**Issue by codemedic** [ihabunek/phormium#9]
May be something to go into the `$_meta` array.
I was looking into using phormium; what stopping me is that it will break my PHP coding standards when working against third-party or mature (already established) schema.

**Comment by ihabunek** [comment]
This is a thing i wanted to add since forever, just never had time. Maybe I'll take it up this month.

**Comment by codemedic** [comment]
That will be fabulous! :)

**Comment by welldtr** [comment]
Hi! Have news? I've been seached too much for it.. :)
